#!/usr/bin/env bash
# WaitSpin MiMo Code statusline runtime launcher.
# The real runtime is generated by `waitspin mimocode install`.
set -euo pipefail

if [ -n "${WAITSPIN_MIMOCODE_RUNTIME:-}" ]; then
  if [ "${WAITSPIN_DEV:-}" != "1" ]; then
    exit 0
  fi
  runtime="$WAITSPIN_MIMOCODE_RUNTIME"
else
  runtime="$HOME/.local/bin/waitspin-mimocode-runtime"
fi

if [ ! -x "$runtime" ]; then
  exit 0
fi

exec "$runtime" "$@"
